import { Program, AnchorProvider, web3 } from '@project-serum/anchor';
import { Connection } from '@solana/web3.js';
import { PointsStoreIDL } from '../types/program';
import type { PointsStore } from '../types/program';

/**
 * Returns the base IDL for the PointsStore program following as generated by Anchor with provided program ID appended to metadata.
 *
 * @param programId - Deployed program ID for the PointsStore program
 * @returns - The base IDL object
 */
function getPointsStoreIDL(programId: web3.PublicKey): unknown {
  const _tmp = PointsStoreIDL;
  _tmp['metadata'] = { address: programId.toBase58() };
  return _tmp;
}

/**
 * Get the PointsStore Anchor program
 * @param connection - the Solana connection object
 * @param programId - Deployed program ID for the PointsStore program
 * @returns the PointsStore anchor program
 */
export function getPointsStoreProgram(
  connection: Connection,
  programId: web3.PublicKey
) {
  const idl = getPointsStoreIDL(programId);
  const provider = new AnchorProvider(connection, null, null);
  const program = new Program(<PointsStore>idl, programId, provider);
  return program;
}
